InternalTransferReferences:
  - train
  - spesenabrechnung

BankProcessingTimeInDays: 3
FilterReferenceWordsForGrouping:
  - muenchen
  - gmbh
  - kartenzahlung
  - plattling
  - kfn
  - visa
ExpenseCategoryDefinition:
  - CategoryName: restaurant
    CategoryTags:
      - '#travelLunch'
      - '#burger'
    CategoryReferences:
      - mcdonalds
      - burger king
      - kfc
  - CategoryName: entertainment
    CategoryTags:
      - '#netflix'
      - '#disney'
    CategoryReferences:
      - netflix
      - disney plus
      - hbo max
IncomeCategoryDefinition:
  - CategoryName: Salary
    CategoryTags:
      - '#MySalary'
      - '#SideJobSalary'
    CategoryReferences:
      - company name
      - sidejob company name
  - CategoryName: Rental
    CategoryTags:
      - '#MyRental'
    CategoryReferences:
      - tentant name
