@startuml

rectangle DataProcessing {
        rectangle BankTransactionProvider
        database BankTransaction
        rectangle Filtering
        cloud NewImplementation {
                rectangle NetTransactionProcessor
                database NetTransaction
        }
        rectangle TypeDecorator
        rectangle Categorizing
        database CategorizedTransaction

        BankTransactionProvider -up-> BankTransaction
        BankTransaction -up-> Filtering
        Filtering -up-> NetTransactionProcessor
        NetTransactionProcessor -right-> NetTransaction
        NetTransaction --> TypeDecorator
        TypeDecorator --> Categorizing
        Categorizing --> CategorizedTransaction
}

rectangle Reporting {
        rectangle TimeAggregation
        rectangle CategoryAggregation
        database Report

        CategorizedTransaction -right-> TimeAggregation
        TimeAggregation --> CategoryAggregation
        CategoryAggregation --> Report
}

@enduml
