name: Build on push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Install pipenv
        run: pip install pipenv
      - name: Setup pipenv dependencies
        run: pipenv install -d
      - name: Setup mypy type dependencies
        run: pipenv run install_types
      - name: Run build
        run: pipenv run build
      - name: Run tests
        run:  pipenv run tests
